fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: 'oussamamethnani@gmail.com'
    sender_name: 'baher@scholl.com'
  profile:
    form:
      type: App\Form\UserProfileType
