twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    date:
        format: d.m.Y, H:i:s
        interval_format: '%%d days'
        timezone: Africa/Tunis
    #exception_controller: App\Controller\RouteController::index
